### PR TITLE
Added blog: Reusability with export and import in Azure Bicep

### PR DESCRIPTION
**Pull request by johnlokerse**
Added my latest blog

Also PR number 100! ;-)

### CODE REVIEW

**Comment by ElYusubov** [comment]
Awesome, I will mention that in our upcoming January build!

**Comment by ElYusubov** [comment]
@johnlokerse , when you have some time, could you check the links that are failing the build?

**Comment by johnlokerse** [comment]
It looks like some kind of browser user-agent issue. There's a new tool created that might fix this: https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file#--update-november-2023-

For now, we can do a workaround by stating that 403 is an "alive status code". What do you think about that @ElYusubov?

**Comment by ElYusubov** [comment]
@johnlokerse please, give it a try when you have some time.
It would be nice to make the building work again.

**Pull request merged**
